# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e356a26f1afa3b9d931cb8b92caf05afd22c337a887f6ef90b9100d2ca459e73603429d9cb3fd363355745a109a29ad45c29bf80c9b6cf0999c9826253e84f68

test:
  secret_key_base: 883e11550cafd9eda3e8e31f8fd49b3202554dcb136856033e0051b5da6b9ba9142d773ed15b0e432c3a409db47afcc2ee5bacbf54d26d46cb402cc87753bf97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
